name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  features:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        feature: [ serde, std, alloc, parse_arg, stringly_conversions, rand, c_raw, proc_attr, hex, apfloat ]
    steps:
      - uses: actions/checkout@v2
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Feature ${{matrix.feature}}
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --no-default-features --features=${{matrix.feature}}
      - name: Defaults + ${{matrix.feature}}
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=${{matrix.feature}}
  toolchains:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [ nightly, beta, stable, 1.41.1 ]
    steps:
      - uses: actions/checkout@v2
      - name: Install rust ${{matrix.toolchain}}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: All features
        if: matrix.toolchain != '1.41.1'
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: "--cfg bench"
        with:
          command: check
          args: --workspace --all-targets --all-features
      - name: All compat features
        if: matrix.toolchain == '1.41.1'
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace --lib --bins --tests --examples --features compat --exclude amplify_apfloat
  dependency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Create dependency
        run: |
          cargo new dep_test
          cd dep_test
          printf 'amplify = { path = "..", features = ["all"] }\namplify_derive = { path = "../derive" }\n\n[workspace]' >> Cargo.toml
      - name: Build dependency
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --verbose
      - name: Clean up
        run: |
          cd ..
          rm -rf dep_test
