name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  features:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        feature: [ serde, std, alloc, parse_arg, stringly_conversions, rand, c_raw, proc_attr, hex, apfloat ]
    steps:
      - uses: actions/checkout@v2
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Feature ${{matrix.feature}}
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --no-default-features --features=${{matrix.feature}}
      - name: Defaults + ${{matrix.feature}}
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=${{matrix.feature}}
  toolchains:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [ nightly, beta, stable, 1.66.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Install rust ${{matrix.toolchain}}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: All features
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: "--cfg bench"
        with:
          command: check
          args: --workspace --all-targets --all-features
