name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  features:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        feature: [ serde, std, alloc, parse_arg, stringly_conversions, rand, c_raw, proc_attr, hex ]
    steps:
      - uses: actions/checkout@v2
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Feature ${{matrix.feature}}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features --features=${{matrix.feature}}
      - name: Defaults + ${{matrix.feature}}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features=${{matrix.feature}}
  toolchains:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [ nightly, beta, stable, 1.41.1 ]
    steps:
      - uses: actions/checkout@v2
      - name: Install rust ${{matrix.toolchain}}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - name: All features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --all-targets --all-features
  ancient:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust 1.36.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.36.0
          override: true
      - name: Clean Cargo.lock
        run: rm -f Cargo.lock
      - name: Fix Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile
          args: --verbose
      - name: Pin serde_yaml
        uses: actions-rs/cargo@v1
        with:
          command: update
          args: -p serde_yaml --precise "0.8.17" --verbose
      - name: Main repo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features
      - name: Derive
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./derive/Cargo.toml
      - name: Syn
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./syn/Cargo.toml
  dependency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Create dependency
        run: |
          cargo new dep_test
          cd dep_test
          printf 'amplify = { path = "..", features = ["all"] }\namplify_derive = { path = "../derive" }\n\n[workspace]' >> Cargo.toml
      - name: Build dependency
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
      - name: Clean up
        run: |
          cd ..
          rm -rf dep_test
