name: Lints

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rustc 1.64.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.64.0
          override: true
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        name: Formatting
        with:
          command: fmt
          args: --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rustc 1.64.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.64.0
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: --workspace --all-features
  wasm-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rustc 1.52.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.52.0
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - uses: jetli/wasm-pack-action@v0.3.0
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown
      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: --workspace --all-features --target wasm32-unknown-unknown
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rustc 1.64.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.64.0
          override: true
          components: rust-docs
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        name: Doc
        with:
          command: doc
          args: --workspace --all-features
